# Generated by Django 3.0 on 2021-04-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='catagory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=200),
        ),
    ]
