# Generated by Django 3.0 on 2021-04-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210425_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_image', models.ImageField(upload_to='img/project/project_image')),
                ('project_brief', models.TextField()),
                ('technologies', models.TextField()),
                ('web_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=255)),
                ('feature_image', models.ImageField(upload_to='img/project/feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project')),
            ],
        ),
    ]
