# Generated by Django 3.0 on 2021-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210426_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.CharField(max_length=255),
        ),
    ]
