# Generated by Django 3.0 on 2021-04-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210426_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
