# Generated by Django 3.0 on 2021-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='fb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
