# Generated by Django 3.0 on 2021-07-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210428_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_name',
        ),
    ]
