# Generated by Django 3.0 on 2021-07-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210716_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
