# Generated by Django 3.0 on 2021-07-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_delete_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
