# Generated by Django 3.0 on 2022-01-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_education_skill_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='duration',
            new_name='result',
        ),
    ]
