# Generated by Django 4.2.3 on 2023-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_biodata_id_alter_catagory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
