# Generated by Django 4.2.3 on 2023-08-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_biodata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(upload_to='img/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='img/projects/'),
        ),
    ]
