# Generated by Django 4.2.3 on 2023-09-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_feature_feature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.catagory'),
        ),
    ]
