# Generated by Django 4.2.3 on 2023-09-20 14:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_project_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_brief',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
